import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  input: {
    width: '85%',
    borderColor: 'red',
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  btnText: {fontSize: 16, color: 'white', fontWeight: 'bold'},
  chatContainer: {
    width: '100%',
    flex: 1,
    marginBottom: 80,
    borderTopColor: '#dadada',
    borderTopWidth: 1,
  },
  button: {
    position: 'absolute',
    bottom: 40,
    right: 10,
    borderRadius: 50,
    height: 50,
    width: 50,
    backgroundColor: 'black',
    borderColor: 'red',
    borderWidth: 1,
    color: 'white',
    shadowColor: 'black',
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  submit: {
    height: 30,
    width: 30,
    borderRadius: 50,
    borderColor: 'red',
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
    backgroundColor: 'red',
  },
  inputContainer: {
    borderTopColor: '#dadada',
    borderTopWidth: 1,
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    flexDirection: 'row',
    padding: 15,
    bottom: 80,
    height: 80,
    width: '100%',
  },
  fab: {
    height: 4,
    width: 60,
    backgroundColor: 'black',
    borderRadius: 10,
    position: 'absolute',
    top: 5,
    left: '42%',
    padding: 5,
  },
  container: {
    position: 'relative',
    backgroundColor: 'white',
    borderTopEndRadius: 25,
    borderTopStartRadius: 25,
    width: '100%',
    flex: 1,
  },
  animeBtn: {
    height: 30,
    width: 30,
    borderRadius: 50,
  },
});

export default styles;
